service: analyze-expenses

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "textract:*"
      Resource: "*"
            

functions:
  analyze:
    url:
      cors: true
    name: analyze-expense
    handler: handler.main

plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: non-linux